baseenv=Environment(CPPPATH=[".","commands","../kaneutil2"])
env=baseenv.Copy(
	CCFLAGS="-Wall"
	)

env.Append(CCFLAGS=" -DDEBUG -DDEBUG_MEMORY -g")
#env.Append(CCFLAGS=" -DDEBUG_FUNC -DDEBUG_NET")
env.Append(CCFLAGS=" -DDEBUG_NET")
#env.Append(CCFLAGS=" -O3")

sources = Split("""
	scc.c
	ability.c
	network.c
	parse.c
	
	commands/msg.c
	commands/list.c
	commands/show.c
	commands/delete.c
	commands/send.c
	""")

libs = Split("""
	ku2
	""")

libpaths = Split("""
	../kaneutil2
	""")

SConscript("../kaneutil2/SConstruct")
Default(env.Program("scc",sources,LIBS=libs,LIBPATH=libpaths))
