#
#	SConstruct file for Kane Utilities 2
#
#	Fri Apr  7 17:16:57 2006
#		J. Anton, Copyright 2006
#

baseenv=Environment(CPPPATH=".")
env=baseenv.Copy(
	CCFLAGS="-Wall"
	)

mode=ARGUMENTS.get("mode","debug")
if mode=="debug":
	env.Append(CCFLAGS=" -g -DDEBUG")
	debug=ARGUMENTS.get("debug","memory,func,log")
	if "memory" in debug:
		env.Append(CCFLAGS=" -DDEBUG_MEMORY")
	if "func" in debug:
		env.Append(CCFLAGS=" -DDEBUG_FUNC")
	if "log" in debug:
		env.Append(CCFLAGS=" -DDEBUG_LOG")
elif mode=="release":
	env.Append(CCFLAGS=" -O3")
	env.Append(LINKFLAGS=" -s")
	debug=""
else:
	print "Invalid mode ( debug|release )"
	sys.exit()

sources = Split("""
	errors/errors.c
	cfgreader/cfg.c
	cfgreader/tree_cfg.c
	log/log.c
	other/other.c
	dialogue/dialogue.c
	""")

Default(env.Library("ku2", sources))

baseenv.Program("ku2test", "test/ku.c", CCFLAGS=env['CCFLAGS'], LIBS="ku2", LIBPATH=".")
