import sys
import os

baseenv=Environment(CPPPATH=[".","../kaneutil2"])
env=baseenv.Copy(
	CCFLAGS="-Wall"
	)

mode=ARGUMENTS.get("mode","debug")
if mode=="debug":
	env.Append(CCFLAGS=" -g -DDEBUG")
	debug=ARGUMENTS.get("debug","memory,net,db,func,log")
	if "memory" in debug:
		env.Append(CCFLAGS=" -DDEBUG_MEMORY")
	if "net" in debug:
		env.Append(CCFLAGS=" -DDEBUG_NET")
	if "db" in debug:
		env.Append(CCFLAGS=" -DDEBUG_DB")
	if "func" in debug:
		env.Append(CCFLAGS=" -DDEBUG_FUNC")
	if "log" in debug:
		env.Append(CCFLAGS=" -DDEBUG_LOG")
elif mode=="release":
	env.Append(CCFLAGS=" -O3")
	debug=""
else:
	print "Invalid mode ( debug|release )"
	sys.exit()



sources = Split("""
	main/sodalis.c
	main/tools.c
	network/net.c
	network/nstore.c
	user/user.c
	user/utree.c
	database/db.c
	parse/parse.c
	""")

libs = Split("""
	ku2
	mysqlclient
	ability
	Magick
	""")

libpaths = Split("""
	../kaneutil2
	/usr/lib/mysql
	ability
	""")

sodalis_flags=env["CCFLAGS"]
SConscript("../kaneutil2/SConstruct")
SConscript("ability/SConstruct","sodalis_flags")
Default(env.Program("sodalisd",sources,LIBS=libs,LIBPATH=libpaths))
