baseenv=Environment(CPPPATH=[".","..","../../kaneutil2"])
env=baseenv.Copy(
	CCFLAGS="-Wall"
	)

Import("sodalis_flags")

#env.Append(CCFLAGS=" -DDEBUG -DDEBUG_MEMORY -DDEBUG_FUNC -g")
env.Replace(CCFLAGS=sodalis_flags)

sources = Split("""
	messages/messages.c
	friends/friends.c
	admin/admin.c
	photos/photos.c
	""")

Default(env.Library("ability", sources))
